export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CUSTOMER_NOT_SYNCED: 'CUSTOMER_NOT_SYNCED',
  CHECKOUT_CREATION_FAILED: 'CHECKOUT_CREATION_FAILED',
  CHECKOUT_ALREADY_EXISTS: 'CHECKOUT_ALREADY_EXISTS',
  PAYMENT_ALREADY_CONFIRMED: 'PAYMENT_ALREADY_CONFIRMED',
  SUBSCRIPTION_ALREADY_PAUSED: 'SUBSCRIPTION_ALREADY_PAUSED',
  SUBSCRIPTION_ALREADY_CANCELED: 'SUBSCRIPTION_ALREADY_CANCELED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EXTERNAL_TIMEOUT: 'EXTERNAL_TIMEOUT',
  RATE_LIMIT: 'RATE_LIMIT',
  EXTERNAL_RESOURCE_NOT_FOUND: 'EXTERNAL_RESOURCE_NOT_FOUND',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  WEBHOOK_ERROR: 'WEBHOOK_ERROR',
  RECONCILIATION_ERROR: 'RECONCILIATION_ERROR',
  RECONCILIATION_IN_PROGRESS: 'RECONCILIATION_IN_PROGRESS',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
