export declare enum UserRole {
    ADMIN = "ADMIN",
    VIEWER = "VIEWER"
}
export declare enum CustomerSyncStatus {
    PENDING = "PENDING",
    SYNCED = "SYNCED",
    FAILED = "FAILED"
}
export declare enum PaymentOrderType {
    ONE_TIME = "ONE_TIME",
    SUBSCRIPTION_INITIAL = "SUBSCRIPTION_INITIAL",
    SUBSCRIPTION_RENEWAL = "SUBSCRIPTION_RENEWAL"
}
export declare enum PaymentMethod {
    PIX = "PIX",
    CREDIT_CARD = "CREDIT_CARD"
}
export declare enum PaymentOrderStatus {
    DRAFT = "DRAFT",
    PENDING = "PENDING",
    CHECKOUT_CREATED = "CHECKOUT_CREATED",
    PROCESSING = "PROCESSING",
    CONFIRMED = "CONFIRMED",
    FAILED = "FAILED",
    EXPIRED = "EXPIRED",
    CANCELED = "CANCELED"
}
export declare enum InternalPaymentStatus {
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    CONFIRMED = "CONFIRMED",
    RECEIVED = "RECEIVED",
    OVERDUE = "OVERDUE",
    REFUNDED = "REFUNDED",
    FAILED = "FAILED",
    CANCELED = "CANCELED"
}
export declare enum SubscriptionCycle {
    MONTHLY = "MONTHLY"
}
export declare enum SubscriptionStatus {
    PENDING = "PENDING",
    ACTIVE = "ACTIVE",
    PAUSED = "PAUSED",
    OVERDUE = "OVERDUE",
    CANCELED = "CANCELED",
    FAILED = "FAILED"
}
export declare enum WebhookEventStatus {
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    PROCESSED = "PROCESSED",
    FAILED = "FAILED",
    IGNORED = "IGNORED"
}
export declare enum AuditEntityType {
    USER = "USER",
    CUSTOMER = "CUSTOMER",
    PAYMENT_ORDER = "PAYMENT_ORDER",
    PAYMENT = "PAYMENT",
    SUBSCRIPTION = "SUBSCRIPTION",
    WEBHOOK = "WEBHOOK",
    RECONCILIATION = "RECONCILIATION"
}
export declare enum AsaasPaymentStatus {
    PENDING = "PENDING",
    RECEIVED = "RECEIVED",
    CONFIRMED = "CONFIRMED",
    OVERDUE = "OVERDUE",
    REFUNDED = "REFUNDED",
    RECEIVED_IN_CASH = "RECEIVED_IN_CASH",
    REFUND_REQUESTED = "REFUND_REQUESTED",
    REFUND_IN_PROGRESS = "REFUND_IN_PROGRESS",
    CHARGEBACK_REQUESTED = "CHARGEBACK_REQUESTED",
    CHARGEBACK_DISPUTE = "CHARGEBACK_DISPUTE",
    AWAITING_CHARGEBACK_REVERSAL = "AWAITING_CHARGEBACK_REVERSAL",
    DUNNING_REQUESTED = "DUNNING_REQUESTED",
    DUNNING_RECEIVED = "DUNNING_RECEIVED",
    AWAITING_RISK_ANALYSIS = "AWAITING_RISK_ANALYSIS"
}
export declare enum AsaasSubscriptionStatus {
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    EXPIRED = "EXPIRED"
}
export declare const ASAAS_PAYMENT_EVENTS: readonly ["PAYMENT_CREATED", "PAYMENT_UPDATED", "PAYMENT_CONFIRMED", "PAYMENT_RECEIVED", "PAYMENT_OVERDUE", "PAYMENT_DELETED", "PAYMENT_REFUNDED", "PAYMENT_RESTORED", "PAYMENT_ANTICIPATED", "PAYMENT_AWAITING_RISK_ANALYSIS", "PAYMENT_APPROVED_BY_RISK_ANALYSIS", "PAYMENT_REPROVED_BY_RISK_ANALYSIS", "PAYMENT_BANK_SLIP_VIEWED", "PAYMENT_CHECKOUT_VIEWED", "PAYMENT_CREDIT_CARD_CAPTURE_REFUSED", "PAYMENT_CHARGEBACK_REQUESTED", "PAYMENT_CHARGEBACK_DISPUTE", "PAYMENT_AWAITING_CHARGEBACK_REVERSAL", "PAYMENT_DUNNING_RECEIVED", "PAYMENT_DUNNING_REQUESTED"];
export declare const ASAAS_SUBSCRIPTION_EVENTS: readonly ["SUBSCRIPTION_CREATED", "SUBSCRIPTION_UPDATED", "SUBSCRIPTION_INACTIVATED", "SUBSCRIPTION_DELETED"];
export declare const ASAAS_CHECKOUT_EVENTS: readonly ["CHECKOUT_CREATED", "CHECKOUT_CANCELED", "CHECKOUT_EXPIRED", "CHECKOUT_PAID"];
export type AsaasPaymentEvent = (typeof ASAAS_PAYMENT_EVENTS)[number];
export type AsaasSubscriptionEvent = (typeof ASAAS_SUBSCRIPTION_EVENTS)[number];
export type AsaasCheckoutEvent = (typeof ASAAS_CHECKOUT_EVENTS)[number];
